apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: xorg-helloworld-replica-set
  labels:
    app: xorg-helloworld-app
spec:
  replicas: 6
  selector:
    matchLabels:
      app: xorg-helloworld-app
  template:
    metadata:
      labels:
        app: xorg-helloworld
    spec:
      containers:
      - name: xorg-helloworld-app
        image: ghcr.io/stacksimplify/kube-helloworld:1.0.0
