apiVersion: apps/v1
kind: Deployment
metadata:
  name: xorgsphere-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: xorgsphere
  template: 
    metadata: # Dictionary
      name: xorgsphere-pod
      labels: # Dictionary 
        app: xorgsphere 
    spec:
      containers: # List
        - name: xorgsphere-container
          image: stacksimplify/kubenginx:1.0.0
          ports:
            - containerPort: 80