apiVersion: v1
kind: Service
metadata:
  name: xorgsphere-loadbalancer
  labels: 
    app: xorgsphere 
spec:
  type: LoadBalancer 
  selector:
    app: xorgsphere 
  ports: 
    - port: 80
      targetPort: 80
